'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace webservicesinNotebook
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="webservicesinNotebook.TZGO_CalculateMenuSoap")>  _
    Public Interface TZGO_CalculateMenuSoap
        
        'CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 YP 以后生成的消息协定未标记为 nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Calculate", ReplyAction:="*")>  _
        Function Calculate(ByVal request As webservicesinNotebook.CalculateRequest) As webservicesinNotebook.CalculateResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CalculateRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Calculate", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As webservicesinNotebook.CalculateRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As webservicesinNotebook.CalculateRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CalculateRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public YP As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public WLBM As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public PANDIANREN As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public GUANQU As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public BEIZHU As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public GUANHAO As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public GAODU As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public YOUWEN As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public QIWEN As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public BZMD As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public BZWD As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public BHXS As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=12)>  _
        Public WDXS As Single
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal YP As String, ByVal WLBM As String, ByVal PANDIANREN As String, ByVal GUANQU As String, ByVal BEIZHU As String, ByVal GUANHAO As String, ByVal GAODU As String, ByVal YOUWEN As String, ByVal QIWEN As String, ByVal BZMD As String, ByVal BZWD As String, ByVal BHXS As String, ByVal WDXS As Single)
            MyBase.New
            Me.YP = YP
            Me.WLBM = WLBM
            Me.PANDIANREN = PANDIANREN
            Me.GUANQU = GUANQU
            Me.BEIZHU = BEIZHU
            Me.GUANHAO = GUANHAO
            Me.GAODU = GAODU
            Me.YOUWEN = YOUWEN
            Me.QIWEN = QIWEN
            Me.BZMD = BZMD
            Me.BZWD = BZWD
            Me.BHXS = BHXS
            Me.WDXS = WDXS
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CalculateResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CalculateResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As webservicesinNotebook.CalculateResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As webservicesinNotebook.CalculateResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CalculateResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public CalculateResult As Single
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CalculateResult As Single)
            MyBase.New
            Me.CalculateResult = CalculateResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface TZGO_CalculateMenuSoapChannel
        Inherits webservicesinNotebook.TZGO_CalculateMenuSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class TZGO_CalculateMenuSoapClient
        Inherits System.ServiceModel.ClientBase(Of webservicesinNotebook.TZGO_CalculateMenuSoap)
        Implements webservicesinNotebook.TZGO_CalculateMenuSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function webservicesinNotebook_TZGO_CalculateMenuSoap_Calculate(ByVal request As webservicesinNotebook.CalculateRequest) As webservicesinNotebook.CalculateResponse Implements webservicesinNotebook.TZGO_CalculateMenuSoap.Calculate
            Return MyBase.Channel.Calculate(request)
        End Function
        
        Public Function Calculate(ByVal YP As String, ByVal WLBM As String, ByVal PANDIANREN As String, ByVal GUANQU As String, ByVal BEIZHU As String, ByVal GUANHAO As String, ByVal GAODU As String, ByVal YOUWEN As String, ByVal QIWEN As String, ByVal BZMD As String, ByVal BZWD As String, ByVal BHXS As String, ByVal WDXS As Single) As Single
            Dim inValue As webservicesinNotebook.CalculateRequest = New webservicesinNotebook.CalculateRequest()
            inValue.Body = New webservicesinNotebook.CalculateRequestBody()
            inValue.Body.YP = YP
            inValue.Body.WLBM = WLBM
            inValue.Body.PANDIANREN = PANDIANREN
            inValue.Body.GUANQU = GUANQU
            inValue.Body.BEIZHU = BEIZHU
            inValue.Body.GUANHAO = GUANHAO
            inValue.Body.GAODU = GAODU
            inValue.Body.YOUWEN = YOUWEN
            inValue.Body.QIWEN = QIWEN
            inValue.Body.BZMD = BZMD
            inValue.Body.BZWD = BZWD
            inValue.Body.BHXS = BHXS
            inValue.Body.WDXS = WDXS
            Dim retVal As webservicesinNotebook.CalculateResponse = CType(Me,webservicesinNotebook.TZGO_CalculateMenuSoap).Calculate(inValue)
            Return retVal.Body.CalculateResult
        End Function
    End Class
End Namespace
