'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.1008
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Inventory.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _3D_GEARS_GEAR7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3D GEARS GEAR7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _6498319_094623725148_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6498319_094623725148_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bq_040() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bq_040", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HDK4_B_3CWIZR6MJZ__CWST() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HDK4_B{3CWIZR6MJZ}]CWST", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hein004() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hein004", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hein015() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hein015", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hein016() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hein016", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hein029() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hein029", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hein15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hein15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hein16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hein16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hein22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hein22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hein28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hein28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hein29() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hein29", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HeinH14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeinH14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HeinH15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeinH15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Kobra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kobra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MiXthepiX_Favorites_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MiXthepiX Favorites logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Osx42() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Osx42", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property psb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("psb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Slayman3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Slayman3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smooth_metal_png_work_group() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smooth_metal_png work-group", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Snap3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Snap3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Toolbar11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Toolbar11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Woa13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Woa13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Woaf31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Woaf31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 大豆筒仓容重维护() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("大豆筒仓容重维护", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 库场参数维护() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("库场参数维护", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 库场跺位导入() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("库场跺位导入", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 开发区仓库品种导入() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("开发区仓库品种导入", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 油品密度维护() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("油品密度维护", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 油品更改提醒() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("油品更改提醒", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 物料编码() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("物料编码", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 物料编码导入() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("物料编码导入", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 用户管理设置() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("用户管理设置", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 罐区任务导入() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("罐区任务导入", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 罐区任务导入格式说明图() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("罐区任务导入格式说明图", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 罐区错误数据校正() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("罐区错误数据校正", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 辅料代码维护() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("辅料代码维护", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
