'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.4963
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  强类型资源类，用于查找本地化字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_Somesoft.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  为使用此强类型资源类的所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _128_咖啡() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("128_咖啡", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _128_咖啡1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("128_咖啡1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chinaz14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chinaz14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chinaz21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chinaz21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Hein28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hein28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Kobra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kobra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Osx42() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Osx42", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property s10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("s10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property s11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("s11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property s12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("s12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property s7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("s7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property s8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("s8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property s9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("s9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property siol1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("siol1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property siol2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("siol2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property siol3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("siol3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property siol4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("siol4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property siol5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("siol5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property siol6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("siol6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 常用系统电脑图标下载24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("常用系统电脑图标下载24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 常用系统电脑图标下载9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("常用系统电脑图标下载9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 方向标() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("方向标", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 系统工具桌面图标下载10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("系统工具桌面图标下载10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 车辆() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("车辆", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property 轿车() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("轿车", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
