'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace QZ_Calcutelate
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="QZ_Calcutelate.QZCANSoap")>  _
    Public Interface QZCANSoap
        
        'CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 guanqu 以后生成的消息协定未标记为 nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Calculate", ReplyAction:="*")>  _
        Function Calculate(ByVal request As QZ_Calcutelate.CalculateRequest) As QZ_Calcutelate.CalculateResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CalculateRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Calculate", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As QZ_Calcutelate.CalculateRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As QZ_Calcutelate.CalculateRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CalculateRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public guanqu As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public wlbm As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public youpin As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public beizhu As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public pandianren As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public jianpanren As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public gaodu As Single
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=7)>  _
        Public youwen As Single
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=8)>  _
        Public midu As Single
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public guanhao As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal guanqu As String, ByVal wlbm As String, ByVal youpin As String, ByVal beizhu As String, ByVal pandianren As String, ByVal jianpanren As String, ByVal gaodu As Single, ByVal youwen As Single, ByVal midu As Single, ByVal guanhao As String)
            MyBase.New
            Me.guanqu = guanqu
            Me.wlbm = wlbm
            Me.youpin = youpin
            Me.beizhu = beizhu
            Me.pandianren = pandianren
            Me.jianpanren = jianpanren
            Me.gaodu = gaodu
            Me.youwen = youwen
            Me.midu = midu
            Me.guanhao = guanhao
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CalculateResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CalculateResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As QZ_Calcutelate.CalculateResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As QZ_Calcutelate.CalculateResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CalculateResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public CalculateResult As Single
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CalculateResult As Single)
            MyBase.New
            Me.CalculateResult = CalculateResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface QZCANSoapChannel
        Inherits QZ_Calcutelate.QZCANSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class QZCANSoapClient
        Inherits System.ServiceModel.ClientBase(Of QZ_Calcutelate.QZCANSoap)
        Implements QZ_Calcutelate.QZCANSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function QZ_Calcutelate_QZCANSoap_Calculate(ByVal request As QZ_Calcutelate.CalculateRequest) As QZ_Calcutelate.CalculateResponse Implements QZ_Calcutelate.QZCANSoap.Calculate
            Return MyBase.Channel.Calculate(request)
        End Function
        
        Public Function Calculate(ByVal guanqu As String, ByVal wlbm As String, ByVal youpin As String, ByVal beizhu As String, ByVal pandianren As String, ByVal jianpanren As String, ByVal gaodu As Single, ByVal youwen As Single, ByVal midu As Single, ByVal guanhao As String) As Single
            Dim inValue As QZ_Calcutelate.CalculateRequest = New QZ_Calcutelate.CalculateRequest()
            inValue.Body = New QZ_Calcutelate.CalculateRequestBody()
            inValue.Body.guanqu = guanqu
            inValue.Body.wlbm = wlbm
            inValue.Body.youpin = youpin
            inValue.Body.beizhu = beizhu
            inValue.Body.pandianren = pandianren
            inValue.Body.jianpanren = jianpanren
            inValue.Body.gaodu = gaodu
            inValue.Body.youwen = youwen
            inValue.Body.midu = midu
            inValue.Body.guanhao = guanhao
            Dim retVal As QZ_Calcutelate.CalculateResponse = CType(Me,QZ_Calcutelate.QZCANSoap).Calculate(inValue)
            Return retVal.Body.CalculateResult
        End Function
    End Class
End Namespace
