'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace LDAPVerification
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="LDAPVerification.LDAPVerificationSoap")>  _
    Public Interface LDAPVerificationSoap
        
        'CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 code 以后生成的消息协定未标记为 nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LoginYesOrNo", ReplyAction:="*")>  _
        Function LoginYesOrNo(ByVal request As LDAPVerification.LoginYesOrNoRequest) As LDAPVerification.LoginYesOrNoResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoginYesOrNoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoginYesOrNo", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As LDAPVerification.LoginYesOrNoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As LDAPVerification.LoginYesOrNoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class LoginYesOrNoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public code As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public UsernameTextBox As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public PasswordTextBox As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal code As String, ByVal UsernameTextBox As String, ByVal PasswordTextBox As String)
            MyBase.New
            Me.code = code
            Me.UsernameTextBox = UsernameTextBox
            Me.PasswordTextBox = PasswordTextBox
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LoginYesOrNoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LoginYesOrNoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As LDAPVerification.LoginYesOrNoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As LDAPVerification.LoginYesOrNoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class LoginYesOrNoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public LoginYesOrNoResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LoginYesOrNoResult As Boolean)
            MyBase.New
            Me.LoginYesOrNoResult = LoginYesOrNoResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface LDAPVerificationSoapChannel
        Inherits LDAPVerification.LDAPVerificationSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class LDAPVerificationSoapClient
        Inherits System.ServiceModel.ClientBase(Of LDAPVerification.LDAPVerificationSoap)
        Implements LDAPVerification.LDAPVerificationSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function LDAPVerification_LDAPVerificationSoap_LoginYesOrNo(ByVal request As LDAPVerification.LoginYesOrNoRequest) As LDAPVerification.LoginYesOrNoResponse Implements LDAPVerification.LDAPVerificationSoap.LoginYesOrNo
            Return MyBase.Channel.LoginYesOrNo(request)
        End Function
        
        Public Function LoginYesOrNo(ByVal code As String, ByVal UsernameTextBox As String, ByVal PasswordTextBox As String) As Boolean
            Dim inValue As LDAPVerification.LoginYesOrNoRequest = New LDAPVerification.LoginYesOrNoRequest()
            inValue.Body = New LDAPVerification.LoginYesOrNoRequestBody()
            inValue.Body.code = code
            inValue.Body.UsernameTextBox = UsernameTextBox
            inValue.Body.PasswordTextBox = PasswordTextBox
            Dim retVal As LDAPVerification.LoginYesOrNoResponse = CType(Me,LDAPVerification.LDAPVerificationSoap).LoginYesOrNo(inValue)
            Return retVal.Body.LoginYesOrNoResult
        End Function
    End Class
End Namespace
