'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace TRUCK_QUEUE
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="TRUCK_QUEUE._0KMSoap")>  _
    Public Interface _0KMSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Auth_User", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Auth_User(ByVal username As String, ByVal password As String, ByVal code As String) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Load_TruckList", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Load_TruckList(ByVal truck_no As String, ByVal code As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Change_Truck", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Change_Truck(ByVal truck_no_old As String, ByVal truck_no_new As String, ByVal tel_no As String, ByVal self As Boolean, ByVal kehumingcheng As String, ByVal pinming As String, ByVal shuliang As Integer, ByVal code As String) As Integer
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface _0KMSoapChannel
        Inherits TRUCK_QUEUE._0KMSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class _0KMSoapClient
        Inherits System.ServiceModel.ClientBase(Of TRUCK_QUEUE._0KMSoap)
        Implements TRUCK_QUEUE._0KMSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Auth_User(ByVal username As String, ByVal password As String, ByVal code As String) As Integer Implements TRUCK_QUEUE._0KMSoap.Auth_User
            Return MyBase.Channel.Auth_User(username, password, code)
        End Function
        
        Public Function Load_TruckList(ByVal truck_no As String, ByVal code As String) As System.Data.DataTable Implements TRUCK_QUEUE._0KMSoap.Load_TruckList
            Return MyBase.Channel.Load_TruckList(truck_no, code)
        End Function
        
        Public Function Change_Truck(ByVal truck_no_old As String, ByVal truck_no_new As String, ByVal tel_no As String, ByVal self As Boolean, ByVal kehumingcheng As String, ByVal pinming As String, ByVal shuliang As Integer, ByVal code As String) As Integer Implements TRUCK_QUEUE._0KMSoap.Change_Truck
            Return MyBase.Channel.Change_Truck(truck_no_old, truck_no_new, tel_no, self, kehumingcheng, pinming, shuliang, code)
        End Function
    End Class
End Namespace
