'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace LYGPORT_OUTSIDE
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="LYGPORT_OUTSIDE.Service1Soap")>  _
    Public Interface Service1Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function HelloWorld() As String
        
        'CODEGEN: 参数“PictureGate”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetInRecord", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetInRecord(ByVal request As LYGPORT_OUTSIDE.GetInRecordRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="veh_return")> LYGPORT_OUTSIDE.GetInRecordResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InsertConsignVehicle", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function InsertConsignVehicle(ByVal cryptogram As String, ByVal vehicle As String, ByVal phone_no As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateConsignVehicle", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UpdateConsignVehicle(ByVal cryptogram As String, ByVal vehicle As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/VehicleInPark", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function VehicleInPark(ByVal cryptogram As String, ByVal vehicle As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/VehiclePark", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function VehiclePark(<System.Runtime.InteropServices.OutAttribute()> ByRef dt As System.Data.DataTable, ByVal cryptogram As String, ByVal vehicle As String, ByVal sqldate As Integer) As String
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetInRecord", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetInRecordRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public cryptogram As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public vehicle As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public externo As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal cryptogram As String, ByVal vehicle As String, ByVal externo As String)
            MyBase.New
            Me.cryptogram = cryptogram
            Me.vehicle = vehicle
            Me.externo = externo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GetInRecordResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class GetInRecordResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public veh_return As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public in_date As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public PictureGate() As Byte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public PictureVehicle() As Byte
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=4)>  _
        Public strErr As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=5)>  _
        Public phone_no As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal veh_return As String, ByVal in_date As String, ByVal PictureGate() As Byte, ByVal PictureVehicle() As Byte, ByVal strErr As String, ByVal phone_no As String)
            MyBase.New
            Me.veh_return = veh_return
            Me.in_date = in_date
            Me.PictureGate = PictureGate
            Me.PictureVehicle = PictureVehicle
            Me.strErr = strErr
            Me.phone_no = phone_no
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface Service1SoapChannel
        Inherits LYGPORT_OUTSIDE.Service1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1SoapClient
        Inherits System.ServiceModel.ClientBase(Of LYGPORT_OUTSIDE.Service1Soap)
        Implements LYGPORT_OUTSIDE.Service1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function HelloWorld() As String Implements LYGPORT_OUTSIDE.Service1Soap.HelloWorld
            Return MyBase.Channel.HelloWorld
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function LYGPORT_OUTSIDE_Service1Soap_GetInRecord(ByVal request As LYGPORT_OUTSIDE.GetInRecordRequest) As LYGPORT_OUTSIDE.GetInRecordResponse Implements LYGPORT_OUTSIDE.Service1Soap.GetInRecord
            Return MyBase.Channel.GetInRecord(request)
        End Function
        
        Public Function GetInRecord(ByVal cryptogram As String, ByVal vehicle As String, ByVal externo As String, <System.Runtime.InteropServices.OutAttribute()> ByRef in_date As String, <System.Runtime.InteropServices.OutAttribute()> ByRef PictureGate() As Byte, <System.Runtime.InteropServices.OutAttribute()> ByRef PictureVehicle() As Byte, <System.Runtime.InteropServices.OutAttribute()> ByRef strErr As String, <System.Runtime.InteropServices.OutAttribute()> ByRef phone_no As String) As String
            Dim inValue As LYGPORT_OUTSIDE.GetInRecordRequest = New LYGPORT_OUTSIDE.GetInRecordRequest()
            inValue.cryptogram = cryptogram
            inValue.vehicle = vehicle
            inValue.externo = externo
            Dim retVal As LYGPORT_OUTSIDE.GetInRecordResponse = CType(Me,LYGPORT_OUTSIDE.Service1Soap).GetInRecord(inValue)
            in_date = retVal.in_date
            PictureGate = retVal.PictureGate
            PictureVehicle = retVal.PictureVehicle
            strErr = retVal.strErr
            phone_no = retVal.phone_no
            Return retVal.veh_return
        End Function
        
        Public Function InsertConsignVehicle(ByVal cryptogram As String, ByVal vehicle As String, ByVal phone_no As String) As String Implements LYGPORT_OUTSIDE.Service1Soap.InsertConsignVehicle
            Return MyBase.Channel.InsertConsignVehicle(cryptogram, vehicle, phone_no)
        End Function
        
        Public Function UpdateConsignVehicle(ByVal cryptogram As String, ByVal vehicle As String) As String Implements LYGPORT_OUTSIDE.Service1Soap.UpdateConsignVehicle
            Return MyBase.Channel.UpdateConsignVehicle(cryptogram, vehicle)
        End Function
        
        Public Function VehicleInPark(ByVal cryptogram As String, ByVal vehicle As String) As String Implements LYGPORT_OUTSIDE.Service1Soap.VehicleInPark
            Return MyBase.Channel.VehicleInPark(cryptogram, vehicle)
        End Function
        
        Public Function VehiclePark(<System.Runtime.InteropServices.OutAttribute()> ByRef dt As System.Data.DataTable, ByVal cryptogram As String, ByVal vehicle As String, ByVal sqldate As Integer) As String Implements LYGPORT_OUTSIDE.Service1Soap.VehiclePark
            Return MyBase.Channel.VehiclePark(dt, cryptogram, vehicle, sqldate)
        End Function
    End Class
End Namespace
